### ISSUE TITLE
Structures

### ISSUE THREAD

**Issue by zRxnx** [PolyhedralDev/Tartarus#1]
Hello!

I would really like this resource to use for a public Minecraft Server, I truly like the new biomes and the generation.

But my current problem is the structures are uncompatible, will it be fixed in the near future with the structures?
I could use an plugin for this, but I don't want to have a entire plugin for all the structures (Overworld, Nether, End).

Have a nice day!

**Comment by Jaddotish** [comment]
Yeah, a newer version of Terra will support custom structures, once that feature drops I'll add in some vanilla and custom structures. Currently there isn't much control over structure generation right now, and I can't really do much about the errors that keep showing up when you enable structures.

The devs are working on 7.0 right now, which, if I recall correctly, will support custom Terra structures.
Sorry about that! I wish I can do something about it but I'm kind of stuck until 7.0 releases 🥲
