### ISSUE TITLE
There no quartz and ancient debris in world

### ISSUE THREAD

**Issue by hxrizxnqq** [PolyhedralDev/Tartarus#6]
that main problem to add this addon in smp

**Comment by Jaddotish** [comment]
Download the zip file (green Code button on the top right) instead of the release, I'll make a release sometime after I've cleaned things up more

**Comment by hxrizxnqq** [comment]
![image](https://github.com/JaddotWuzHere/Tartarus/assets/125192601/ea8b0fa3-b6cc-4ef3-a1b3-91f1f20aee65)

**Comment by hxrizxnqq** [comment]
> ![image](https://private-user-images.githubusercontent.com/125192601/300288639-ea8b0fa3-b6cc-4ef3-a1b3-91f1f20aee65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NzA0NTUsIm5iZiI6MTcwNjQ3MDE1NSwicGF0aCI6Ii8xMjUxOTI2MDEvMzAwMjg4NjM5LWVhOGIwZmEzLWI2Y2MtNGVmMy1hMWIzLTkxZjFmMjBhZWU2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxOTI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGE0Yjg4MjkyOTI0MDJhMTliY2EzNTIzMTZkYmFjMmRiOWU5NjkyNzVlNDI2MmNhMGYyMmM4YWJkNTNjOWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Em9k98Zle47ApuS-2Q5ToG2NbbxvO2iOQ9zP2z6iGt8)

when i regenerating new world, addon doesn't work and generating default nether

**Comment by Jaddotish** [comment]
Join the Terra Discord and create a support ticket.
